name: Bike Share Model application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: entering correct directory
      run: |
        cd bikeshare_project
        pwd
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements/requirements.txt ]; then pip install -r requirements/requirements.txt; fi
#    - name: Code formatting with black
#      run: |
#        black bikeshare_model/*.py
    - name: Lint with pylint
      run: |
        pylint --disable=R,C --extension-pkg-whitelist='pydantic' bikeshare_model/
    - name: Train the model
      run: |
        python bikeshare_model/train_pipeline.py
    - name: Test with pytest
      run: |
        pytest
